services:
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "6379"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: ${MEILI_NO_ANALYTICS}
      MEILI_ENV: ${MEILI_ENV}
    ports:
      - ${MEILI_PORT}:7700
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped